sudo: required

language: generic  
services:
    - docker

before-install:
    - docker build -t dipuvish5/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true dipuvish5/docker-react npm run test -- --coverage